
title:
  en: Your awesome title
  fr: Votre titre génial

description:
  en: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  fr: Écrivez une super description de votre nouveau site ici. Vous pouvez modifier cette ligne dans _config.yml. Elle apparaîtra dans la balise meta description (pour les résultats sur Google) et dans le fil RSS feed.xml.

collections:
  docs:
    output: true
    permalink: /:path

url: "https://mathieuandrade.github.io"
baseurl: "/documentation.gladysproject.com.jekyll"

# Social network
twitter_username: gladysproject
github_username:  gladysproject
facebook_username: gladysproject
instagram_username: gladysproject

## I18N
languages: ["en", "fr"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  fr: Français
  en: English

#SEO plugins infos
twitter:
  username: gladysproject
logo: /assets/image/gladys-logo.png
social:
  name: Gladys Project
  links:
    - https://twitter.com/gladysproject
    - https://www.facebook.com/gladysproject
    - https://www.instagram.com/gladysproject
    - https://github.com/gladysproject

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
